@startuml
'https://plantuml.com/class-diagram

static class Logger
class View
class Extension
class ThreeMFReader
class ThreeMFWorkspaceReader
class MetadataReader {
    +dict _metadata
    +string _path_file
    +string _file
    -checkFile(_file: String): void
    +readMetadata(metadata: dict): dict
}
class Application {
    +run()
}
class GuiMetadataReader {

    +metadata: dict
    +openWindow(): void
    +projectMetadata(metadata: dict): void

}
class PluginRegistery {
    +loadPlugin(name: string): Plugin
    +loadPlugins(type: string): list
    +getMetaData(name: string): dict
    +getAllMetaData(type: string): list
}
Logger <.. ThreeMFReader
Logger <.. ThreeMFWorkspaceReader
ThreeMFWorkspaceReader <--- MetadataReader : metadata, 0..1
ThreeMFReader ---> MetadataReader
MetadataReader --|> PluginRegistery
MetadataReader <-- Logger
MetadataReader <.. GuiMetadataReader: "+metadata" 1
View <|-- GuiMetadataReader : " +metadata "  1..*
Extension <|-- GuiMetadataReader
PluginRegistery --* Application: "+pluginRegistery"  1
@enduml