@startuml
'https://plantuml.com/use-case-diagram

left to right direction
skinparam packageStyle rectangle
actor User

rectangle 3MFGuiReader {
    User -- (OpenWindow)
    (OpenWindow) ...> (ReadMetadata): include
    User -- (ReadMetadataFromWindow)
    (ReadMetadataFromWindow) ..> (ReadMetadata): include
    (ProjectMetadata) .> (ReadMetadata): include
}

@enduml